/** Shared calendar day (US Eastern) for News tab data cache keys — all users get the same bucket per day. */
export function newsCalendarDayET(): string {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "America/New_York",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(new Date())
}

/**
 * How long Next.js Data Cache keeps News tab fetches.
 * 25 hours: entries are daily snapshots generated by the 5:00 UTC warm-cache
 * cron. Keys already include the ET calendar day, so rollover happens at
 * midnight ET; the window just needs to outlive the day plus cron slack so
 * user visits never trigger regeneration.
 */
export const NEWS_TAB_REVALIDATE_SECONDS = 90000
